const mockData = [
    {
      id: 1,
      title: "Product 1",
      description: "This is a description of product 1.",
      image: "https://via.placeholder.com/150",
      price: "$29.99",
      BestSell: true,
    },
    {
      id: 2,
      title: "Product 2",
      description: "This is a description of product 2.",
      image: "https://via.placeholder.com/150",
      price: "$39.99",
      BestSell: false,
    },
    {
      id: 3,
      title: "Product 3",
      description: "This is a description of product 3.",
      image: "https://via.placeholder.com/150",
      price: "$49.99",
      BestSell: true,
    },
    {
      id: 4,
      title: "Product 4",
      description: "This is a description of product 4.",
      image: "https://via.placeholder.com/150",
      price: "$59.99",
      BestSell: false,
    },
    {
      id: 5,
      title: "Product 5",
      description: "This is a description of product 5.",
      image: "https://via.placeholder.com/150",
      price: "$69.99",
      BestSell: true,
    },
    {
      id: 6,
      title: "Product 6",
      description: "This is a description of product 6.",
      image: "https://via.placeholder.com/150",
      price: "$79.99",
      BestSell: false,
    },
    {
      id: 7,
      title: "Product 7",
      description: "This is a description of product 7.",
      image: "https://via.placeholder.com/150",
      price: "$89.99",
      BestSell: true,
    },
    {
      id: 8,
      title: "Product 8",
      description: "This is a description of product 8.",
      image: "https://via.placeholder.com/150",
      price: "$99.99",
      BestSell: false,
    },
    {
      id: 9,
      title: "Product 9",
      description: "This is a description of product 9.",
      image: "https://via.placeholder.com/150",
      price: "$109.99",
      BestSell: true,
    },
    {
      id: 10,
      title: "Product 10",
      description: "This is a description of product 10.",
      image: "https://via.placeholder.com/150",
      price: "$119.99",
      BestSell: false,
    },
    {
      id: 11,
      title: "Product 11",
      description: "This is a description of product 11.",
      image: "https://via.placeholder.com/150",
      price: "$129.99",
      BestSell: true,
    },
    {
      id: 12,
      title: "Product 12",
      description: "This is a description of product 12.",
      image: "https://via.placeholder.com/150",
      price: "$139.99",
      BestSell: false,
    },
    {
      id: 13,
      title: "Product 13",
      description: "This is a description of product 13.",
      image: "https://via.placeholder.com/150",
      price: "$149.99",
      BestSell: true,
    },
    {
      id: 14,
      title: "Product 14",
      description: "This is a description of product 14.",
      image: "https://via.placeholder.com/150",
      price: "$159.99",
      BestSell: false,
    },
    {
      id: 15,
      title: "Product 15",
      description: "This is a description of product 15.",
      image: "https://via.placeholder.com/150",
      price: "$169.99",
      BestSell: true,
    },
    {
      id: 16,
      title: "Product 16",
      description: "This is a description of product 16.",
      image: "https://via.placeholder.com/150",
      price: "$179.99",
      BestSell: false,
    },
    {
      id: 17,
      title: "Product 17",
      description: "This is a description of product 17.",
      image: "https://via.placeholder.com/150",
      price: "$189.99",
      BestSell: true,
    },
    {
      id: 18,
      title: "Product 18",
      description: "This is a description of product 18.",
      image: "https://via.placeholder.com/150",
      price: "$199.99",
      BestSell: false,
    },
    {
      id: 19,
      title: "Product 19",
      description: "This is a description of product 19.",
      image: "https://via.placeholder.com/150",
      price: "$209.99",
      BestSell: true,
    },
    {
      id: 20,
      title: "Product 20",
      description: "This is a description of product 20.",
      image: "https://via.placeholder.com/150",
      price: "$219.99",
      BestSell: false,
    },
  ];
  
  export default mockData;
  